// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopiVerse.Data;

#nullable disable

namespace ShopiVerse.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20240127191907_SeedAllTable")]
    partial class SeedAllTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopiVerse.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Price = 100.00m,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            Price = 150.00m,
                            ProductId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 2,
                            Price = 200.00m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 2,
                            Price = 250.00m,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 3,
                            Price = 300.00m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 3,
                            Price = 350.00m,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 4,
                            Price = 400.00m,
                            ProductId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 4,
                            Price = 450.00m,
                            ProductId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 5,
                            Price = 500.00m,
                            ProductId = 9,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 5,
                            Price = 550.00m,
                            ProductId = 10,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("ShopiVerse.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Beşiktaş Mahallesi, No:1",
                            City = "İstanbul",
                            District = "Beşiktaş",
                            Name = "Ali",
                            Surname = "Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Çankaya Mahallesi, No:2",
                            City = "Ankara",
                            District = "Çankaya",
                            Name = "Ayşe",
                            Surname = "Kaya"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bornova Mahallesi, No:3",
                            City = "İzmir",
                            District = "Bornova",
                            Name = "Mehmet",
                            Surname = "Öz"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Nilüfer Mahallesi, No:4",
                            City = "Bursa",
                            District = "Nilüfer",
                            Name = "Elif",
                            Surname = "Demir"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Konyaaltı Mahallesi, No:5",
                            City = "Antalya",
                            District = "Konyaaltı",
                            Name = "Ahmet",
                            Surname = "Can"
                        },
                        new
                        {
                            Id = 6,
                            Address = "İlkadım Mahallesi, No:6",
                            City = "Samsun",
                            District = "İlkadım",
                            Name = "Zeynep",
                            Surname = "Balcı"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ortahisar Mahallesi, No:7",
                            City = "Trabzon",
                            District = "Ortahisar",
                            Name = "Kemal",
                            Surname = "Yıldız"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Tepebaşı Mahallesi, No:8",
                            City = "Eskişehir",
                            District = "Tepebaşı",
                            Name = "Seda",
                            Surname = "Akar"
                        },
                        new
                        {
                            Id = 9,
                            Address = "İzmit Mahallesi, No:9",
                            City = "Kocaeli",
                            District = "İzmit",
                            Name = "Murat",
                            Surname = "Tekin"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Şahinbey Mahallesi, No:10",
                            City = "Gaziantep",
                            District = "Şahinbey",
                            Name = "Esra",
                            Surname = "Kurt"
                        });
                });

            modelBuilder.Entity("ShopiVerse.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 500.00m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 400.00m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 300.00m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            OrderDate = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 200.00m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            OrderDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 100.00m
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 6,
                            OrderDate = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 600.00m
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 7,
                            OrderDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 700.00m
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 8,
                            OrderDate = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 800.00m
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 9,
                            OrderDate = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 900.00m
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 10,
                            OrderDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 1000.00m
                        });
                });

            modelBuilder.Entity("ShopiVerse.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 150.00m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 3,
                            UnitPrice = 200.00m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 2,
                            UnitPrice = 250.00m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 300.00m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 6,
                            Quantity = 2,
                            UnitPrice = 350.00m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 400.00m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 450.00m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 9,
                            Quantity = 3,
                            UnitPrice = 500.00m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 5,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 550.00m
                        });
                });

            modelBuilder.Entity("ShopiVerse.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ürün 1",
                            Price = 100.00m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ürün 2",
                            Price = 150.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ürün 3",
                            Price = 200.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ürün 4",
                            Price = 250.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ürün 5",
                            Price = 300.00m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ürün 6",
                            Price = 350.00m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ürün 7",
                            Price = 400.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ürün 8",
                            Price = 450.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ürün 9",
                            Price = 500.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ürün 10",
                            Price = 550.00m,
                            StockQuantity = 45
                        });
                });

            modelBuilder.Entity("ShopiVerse.Models.Cart", b =>
                {
                    b.HasOne("ShopiVerse.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopiVerse.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopiVerse.Models.Order", b =>
                {
                    b.HasOne("ShopiVerse.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ShopiVerse.Models.OrderDetail", b =>
                {
                    b.HasOne("ShopiVerse.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopiVerse.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopiVerse.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ShopiVerse.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ShopiVerse.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
